-- MySQL Script generated by MySQL Workbench
-- Thu Dec  4 12:46:32 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AgricolaD_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AgricolaD_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AgricolaD_bd` DEFAULT CHARACTER SET utf8 ;
USE `AgricolaD_bd` ;

-- -----------------------------------------------------
-- Table `AgricolaD_bd`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgricolaD_bd`.`Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `unidadMedida` VARCHAR(45) NOT NULL,
  `precioUnitario` DECIMAL(5,2) NOT NULL,
  `cantidadDisponible` INT NOT NULL,
  `fechaRegistro` DATE NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProducto`),
  UNIQUE INDEX `idProducto_UNIQUE` (`idProducto` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AgricolaD_bd`.`Distribucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgricolaD_bd`.`Distribucion` (
  `idDistribucion` INT NOT NULL AUTO_INCREMENT,
  `fechaSalida` DATE NOT NULL,
  `fechaEntrega` DATE NOT NULL,
  `rutaAsignada` VARCHAR(45) NOT NULL,
  `transportista` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDistribucion`),
  UNIQUE INDEX `idDistribucion_UNIQUE` (`idDistribucion` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AgricolaD_bd`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgricolaD_bd`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `fechaPedido` DATE NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `direccionEntrega` VARCHAR(45) NOT NULL,
  `total` INT NOT NULL,
  `Distribucion_idDistribucion` INT NOT NULL,
  PRIMARY KEY (`idPedido`),
  UNIQUE INDEX `idPedido_UNIQUE` (`idPedido` ASC) VISIBLE,
  INDEX `fk_Pedido_Distribucion1_idx` (`Distribucion_idDistribucion` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Distribucion1`
    FOREIGN KEY (`Distribucion_idDistribucion`)
    REFERENCES `AgricolaD_bd`.`Distribucion` (`idDistribucion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AgricolaD_bd`.`DetallePedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgricolaD_bd`.`DetallePedido` (
  `idDetallePedido` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `precioUnitario` DECIMAL(5,2) NOT NULL,
  `subtotal` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  PRIMARY KEY (`idDetallePedido`),
  UNIQUE INDEX `idDetallePedido_UNIQUE` (`idDetallePedido` ASC) VISIBLE,
  INDEX `fk_DetallePedido_Producto_idx` (`Producto_idProducto` ASC) VISIBLE,
  INDEX `fk_DetallePedido_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  CONSTRAINT `fk_DetallePedido_Producto`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `AgricolaD_bd`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetallePedido_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `AgricolaD_bd`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AgricolaD_bd`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgricolaD_bd`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `idCliente_UNIQUE` (`idCliente` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AgricolaD_bd`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgricolaD_bd`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_Usuario_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `AgricolaD_bd`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AgricolaD_bd`.`Notificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgricolaD_bd`.`Notificacion` (
  `idNotificacion` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `fechaEnvio` DATE NOT NULL,
  `mensaje` VARCHAR(45) NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  PRIMARY KEY (`idNotificacion`),
  UNIQUE INDEX `idNotificacion_UNIQUE` (`idNotificacion` ASC) VISIBLE,
  INDEX `fk_Notificacion_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_Notificacion_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  CONSTRAINT `fk_Notificacion_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `AgricolaD_bd`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Notificacion_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `AgricolaD_bd`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AgricolaD_bd`.`Reporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgricolaD_bd`.`Reporte` (
  `idReporte` INT NOT NULL AUTO_INCREMENT,
  `tipoReporte` VARCHAR(45) NOT NULL,
  `fechaGeneracion` DATE NOT NULL,
  `rangoFecha` VARCHAR(45) NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idReporte`),
  UNIQUE INDEX `idReporte_UNIQUE` (`idReporte` ASC) VISIBLE,
  INDEX `fk_Reporte_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Reporte_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `AgricolaD_bd`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


ALTER TABLE Usuario
MODIFY COLUMN `contraseña` VARCHAR(255) NOT NULL;

